### ISSUE TITLE
Searchable/Filter and Sortable Text Fields for data-table

### ISSUE THREAD

**Issue by st-clair-clarke** [MikeMitterer/dart-material-design-lite#29]
Hi MIke,
Is it possible to add a Search/filter text field on data-table (both)? Also, it would be great if both had sortable columns.

Cheers

**Comment by jfphilbin** [comment]
I agree.  My priorities would be 1) search, 2) sort, 3) filter.

**Comment by st-clair-clarke** [comment]
I was thinking that the filter would simply display the relevant row containing the input entry. That way if there is a long list one could find the relevant one quite quickly allowing its selection/deselection. How do you see the search jfphilbin?

**Comment by jfphilbin** [comment]
I was thinking of something like MS Excel, where in Filter mode each column would either have a pre-computed set of filters, or would allow a regexp.  When activated the filter would display only those rows that have a match in the filtered column.

For search I thought it should allow simple string or regexp matching.  Since all fields in the table are [String]s, it should return any row that has a matching field (in any column).

**Comment by st-clair-clarke** [comment]
That sounds perfect jfphilbin. I support both. Only issue is we are not sure what the developer of MDL-lite is thinking. Would appreciate his comment.

**Comment by MikeMitterer** [comment]
Does this sample help?
http://samples.material-design-lite.pub/mdld_repeat_data-table/index.html

GH:
https://github.com/MikeMitterer/dart-material-design-lite-site/blob/master/samples/mdld_repeat_data-table/web/main.dart
